.PHONY: start dev build test lint migration-run migration-revert

start:
	npm run start

dev:
	npm run start:dev

build:
	npm run build

test:
	npm run test

lint:
	npm run lint

migration-run:
	npm run migration:run

migration-revert:
	npm run migration:revert
